version: '3.8'

services:
  fastapi:
    build: 
      context: ./backend
    ports:
      - "8001:8001"
    command: uvicorn api:app --host 0.0.0.0 --port 8001
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
